# Generated by Django 4.1.10 on 2025-11-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_fecha_agenda_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
