# Generated by Django 4.1.10 on 2025-11-10 04:51

from django.db import migrations, models
import django.db.models.deletion


def migrar_horarios_a_horarioagenda(apps, schema_editor):
    """
    Migra los datos existentes de Agenda.horarios (ManyToMany) 
    a HorarioAgenda (through model).
    """
    Agenda = apps.get_model('core', 'Agenda')
    HorarioAgenda = apps.get_model('core', 'HorarioAgenda')
    
    # Para cada agenda, crear HorarioAgenda para cada horario asociado
    for agenda in Agenda.objects.all():
        # Obtener los horarios asociados a través de la tabla intermedia ManyToMany
        horarios = agenda.horarios.all()
        for horario in horarios:
            # Crear HorarioAgenda sin reservado_por (disponible)
            HorarioAgenda.objects.get_or_create(
                agenda=agenda,
                horario=horario,
                defaults={'reservado_por': None}
            )


def revertir_migracion_horarios(apps, schema_editor):
    """
    Función de reversión: elimina todos los HorarioAgenda.
    Los horarios volverán a estar en la relación ManyToMany directa.
    """
    HorarioAgenda = apps.get_model('core', 'HorarioAgenda')
    HorarioAgenda.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        # Paso 1: Crear el modelo HorarioAgenda
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agenda')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horarios')),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.persona')),
            ],
            options={
                'verbose_name': 'Horario de Agenda',
                'verbose_name_plural': 'Horarios de Agenda',
                'unique_together': {('agenda', 'horario')},
            },
        ),
        # Paso 2: Migrar los datos existentes ANTES de cambiar el campo
        migrations.RunPython(migrar_horarios_a_horarioagenda, revertir_migracion_horarios),
        # Paso 3: Eliminar el campo ManyToMany antiguo
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        # Paso 4: Crear el nuevo campo ManyToMany con through
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(through='core.HorarioAgenda', to='core.horarios'),
        ),
    ]
