# Generated by Django 4.1.10 on 2025-11-10 02:41

from django.db import migrations, models
import django.utils.timezone


def agregar_fecha_a_notificaciones_existentes(apps, schema_editor):
    """
    Agrega fecha a las notificaciones existentes usando la fecha del comentario o ahora.
    """
    NotificacionSuperusuario = apps.get_model('core', 'NotificacionSuperusuario')
    for notif in NotificacionSuperusuario.objects.all():
        if notif.comentario:
            # Usar la fecha del comentario si existe
            notif.fecha = notif.comentario.date_added
        else:
            # Usar la fecha actual si no hay comentario
            notif.fecha = django.utils.timezone.now()
        notif.save()


def revertir_fecha(apps, schema_editor):
    """
    Función de reversión (no hace nada, solo para compatibilidad).
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horarioagenda_alter_agenda_horarios'),
    ]

    operations = [
        # Agregar campo fecha como nullable primero
        migrations.AddField(
            model_name='notificacionsuperusuario',
            name='fecha',
            field=models.DateTimeField(null=True, blank=True),
        ),
        # Poblar fechas existentes
        migrations.RunPython(agregar_fecha_a_notificaciones_existentes, revertir_fecha),
        # Hacer el campo no nullable y con auto_now_add
        migrations.AlterField(
            model_name='notificacionsuperusuario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        # Agregar Meta ordering
        migrations.AlterModelOptions(
            name='notificacionsuperusuario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificación Superusuario', 'verbose_name_plural': 'Notificaciones Superusuario'},
        ),
    ]
