# Generated by Django 4.1.10 on 2025-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251110_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='psicologo',
            options={'ordering': ['nombre'], 'verbose_name': 'Psicólogo', 'verbose_name_plural': 'Psicólogos'},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'ordering': ['idTipoUsuario'], 'verbose_name': 'Tipo de Usuario', 'verbose_name_plural': 'Tipos de Usuario'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='horarioagenda',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Apellido_usuario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(db_index=True, max_length=50, unique=True, verbose_name='Correo_usuario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Nombre_usuario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Rut_usuario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='telefono_psicologo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'date_added'], name='core_commen_post_id_01b610_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'date_added'], name='core_commen_author__433ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['persona', '-fecha', 'leida'], name='core_notifi_persona_c3621c_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['apellido', 'nombre'], name='core_person_apellid_8a90b9_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['correo'], name='core_person_correo_514e43_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['tipousuario'], name='core_person_tipousu_c3173f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_added', 'hilo'], name='core_post_date_ad_4fa44f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-date_added'], name='core_post_author__656519_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='core_post_title_2b847b_idx'),
        ),
    ]
