# Generated by Django 4.1.10 on 2025-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reportado',
            field=models.BooleanField(default=False, verbose_name='Reportado por contenido inapropiado'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imagen del post'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderado',
            field=models.BooleanField(default=False, verbose_name='Moderado'),
        ),
        migrations.AddField(
            model_name='post',
            name='reportado',
            field=models.BooleanField(default=False, verbose_name='Reportado por contenido inapropiado'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de video (YouTube/Vimeo)'),
        ),
    ]
