# Generated by Django 4.1.10 on 2025-11-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_moderation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nombre de sala')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_videocall', to='core.agenda', verbose_name='Agenda asociada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to='core.persona', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sala de Videollamada',
                'verbose_name_plural': 'Salas de Videollamada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1000, verbose_name='UID de Agora')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de ingreso')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('insession', models.BooleanField(db_index=True, default=True, verbose_name='En sesión')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_salas', to='core.persona', verbose_name='Persona')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.videocallroom', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Miembro de Sala',
                'verbose_name_plural': 'Miembros de Sala',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='core.persona', verbose_name='Autor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.videocallroom', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videocallroom',
            index=models.Index(fields=['name', 'is_active'], name='core_videoc_name_8dc815_idx'),
        ),
        migrations.AddIndex(
            model_name='videocallroom',
            index=models.Index(fields=['created_by', '-created_at'], name='core_videoc_created_81df60_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room', 'insession'], name='core_roomme_room_id_3b528a_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['persona', '-joined_at'], name='core_roomme_persona_e8a51c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('room', 'uid')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='core_chatme_room_id_43aab9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['author', 'created_at'], name='core_chatme_author__5c3290_idx'),
        ),
    ]
