# Generated by Django 4.1.10 on 2025-11-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_videocallroom_roommember_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='role',
            field=models.CharField(choices=[('psicologo', 'Psicólogo'), ('practicante', 'Practicante'), ('paciente', 'Paciente'), ('audience', 'Audiencia')], db_index=True, default='paciente', help_text='Rol del participante en la sala', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='videocallroom',
            name='max_participants',
            field=models.IntegerField(default=10, help_text='Para eventos grupales, límite de participantes', verbose_name='Máximo de participantes'),
        ),
        migrations.AddField(
            model_name='videocallroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Sesión Privada'), ('group', 'Evento Grupal')], db_index=True, default='private', help_text='Sesión Privada: psicólogo + practicante + paciente. Evento Grupal: psicólogo + muchos usuarios', max_length=20, verbose_name='Tipo de sala'),
        ),
    ]
