# Generated by Django 4.1.10 on 2025-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_roommember_role_videocallroom_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallroom',
            name='is_couple_therapy',
            field=models.BooleanField(db_index=True, default=False, help_text='Si está activado, permite hasta 5 participantes (psicólogo + practicante + pareja)', verbose_name='Terapia de pareja'),
        ),
        migrations.AlterField(
            model_name='videocallroom',
            name='max_participants',
            field=models.IntegerField(default=3, help_text='Sesión privada: 3-5 participantes. Evento grupal: hasta 50 participantes', verbose_name='Máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='videocallroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Sesión Privada'), ('group', 'Evento Grupal')], db_index=True, default='private', help_text='Sesión Privada: psicólogo + practicante + paciente(s). Evento Grupal: psicólogo + muchos usuarios', max_length=20, verbose_name='Tipo de sala'),
        ),
    ]
