# Generated by Django 4.1.10 on 2025-11-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_videocallroom_is_couple_therapy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chatbot', to='core.persona', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GrupoApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del grupo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tema', models.CharField(choices=[('ansiedad', 'Ansiedad'), ('depresion', 'Depresión'), ('duelo', 'Duelo y Pérdida'), ('estres', 'Estrés'), ('autoestima', 'Autoestima'), ('relaciones', 'Relaciones'), ('adicciones', 'Adicciones'), ('trauma', 'Trauma'), ('otro', 'Otro')], db_index=True, max_length=50, verbose_name='Tema')),
                ('max_miembros', models.IntegerField(default=20, verbose_name='Máximo de miembros')),
                ('is_activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_publico', models.BooleanField(db_index=True, default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to='core.persona', verbose_name='Creado por')),
                ('psicologo_moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_moderados', to='core.psicologo', verbose_name='Psicólogo moderador')),
                ('sala_videocall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_apoyo', to='core.videocallroom', verbose_name='Sala de videollamada')),
            ],
            options={
                'verbose_name': 'Grupo de Apoyo',
                'verbose_name_plural': 'Grupos de Apoyo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(db_index=True, verbose_name='Fecha programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('tema_sesion', models.CharField(blank=True, max_length=200, verbose_name='Tema de la sesión')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de la sesión')),
                ('is_activa', models.BooleanField(db_index=True, default=False, verbose_name='Sesión activa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.grupoapoyo', verbose_name='Grupo')),
                ('psicologo_facilitador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.psicologo', verbose_name='Psicólogo facilitador')),
                ('sala_videocall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesion_grupo', to='core.videocallroom', verbose_name='Sala de videollamada')),
            ],
            options={
                'verbose_name': 'Sesión de Grupo',
                'verbose_name_plural': 'Sesiones de Grupo',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='RecursoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('articulo', 'Artículo'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('enlace', 'Enlace'), ('otro', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_grupos/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('compartido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_compartidos', to='core.persona', verbose_name='Compartido por')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.grupoapoyo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Recurso de Grupo',
                'verbose_name_plural': 'Recursos de Grupo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de unión')),
                ('is_activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('es_moderador', models.BooleanField(default=False, verbose_name='Es moderador')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='core.grupoapoyo', verbose_name='Grupo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_miembro', to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupo',
                'ordering': ['-fecha_union'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA'), ('system', 'Sistema')], db_index=True, default='user', max_length=20, verbose_name='Rol')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('is_crisis_detected', models.BooleanField(db_index=True, default=False, verbose_name='Crisis detectada')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.chatconversation', verbose_name='Conversación')),
                ('psicologo_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.psicologo', verbose_name='Psicólogo recomendado')),
            ],
            options={
                'verbose_name': 'Mensaje Chatbot',
                'verbose_name_plural': 'Mensajes Chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sesiongrupo',
            index=models.Index(fields=['grupo', '-fecha_programada'], name='core_sesion_grupo_i_2fd40f_idx'),
        ),
        migrations.AddIndex(
            model_name='sesiongrupo',
            index=models.Index(fields=['is_activa'], name='core_sesion_is_acti_a76eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='recursogrupo',
            index=models.Index(fields=['grupo', '-created_at'], name='core_recurs_grupo_i_d852b8_idx'),
        ),
        migrations.AddIndex(
            model_name='recursogrupo',
            index=models.Index(fields=['tipo'], name='core_recurs_tipo_7de58e_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrogrupo',
            index=models.Index(fields=['grupo', 'is_activo'], name='core_miembr_grupo_i_40f9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrogrupo',
            index=models.Index(fields=['persona', 'is_activo'], name='core_miembr_persona_07f131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='miembrogrupo',
            unique_together={('grupo', 'persona')},
        ),
        migrations.AddIndex(
            model_name='grupoapoyo',
            index=models.Index(fields=['tema', 'is_activo'], name='core_grupoa_tema_78ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoapoyo',
            index=models.Index(fields=['is_publico', 'is_activo'], name='core_grupoa_is_publ_2c8e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagebot',
            index=models.Index(fields=['conversation', 'created_at'], name='core_chatme_convers_4eee3c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagebot',
            index=models.Index(fields=['is_crisis_detected'], name='core_chatme_is_cris_815664_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['persona', '-updated_at'], name='core_chatco_persona_151de8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['is_active', '-updated_at'], name='core_chatco_is_acti_06610c_idx'),
        ),
    ]
