"""
Django settings for ZenMindConnect project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción, SECRET_KEY DEBE estar en .env. Sin default por seguridad.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False para seguridad. Solo True en desarrollo local.
DEBUG = config('DEBUG', default=False, cast=bool)

# Permitir todos los hosts en desarrollo para ngrok (cambiar en producción)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
# En desarrollo, permitir cualquier host de ngrok
if DEBUG:
    ALLOWED_HOSTS = ['*']  # Permitir todos los hosts en desarrollo

# Testing mode - detectado automáticamente
import sys
TESTING = 'test' in sys.argv or 'pytest' in sys.argv[0] or 'unittest' in sys.argv[0]

# Messages Configuration
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Authentication URLs
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "log"
LOGIN_URL = "log"

# Application definition

INSTALLED_APPS = [
    'daphne',  # Servidor ASGI para WebSockets (debe ir primero)
    'channels',  # Django Channels para WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Para sitemap.xml
    'compressor',  # Para minificación CSS/JS
    'autoslug',
    'core',
]

# Compressor configuration para minificación CSS/JS
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = not DEBUG  # Solo en producción
COMPRESS_OFFLINE = False  # Minificación en tiempo real (más flexible)
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Debe ir ANTES de AntiBotMiddleware para que request.user exista
    'core.middleware.AntiBotMiddleware',  # Protección contra bots y scraping
    'core.middleware_csp.CSPMiddleware',  # Content Security Policy
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ZenMindConnect.urls'

# Logging Configuration
# Crear directorio de logs si no existe
logs_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {name} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'security': {
            'format': '{levelname} {asctime} SECURITY {module} IP:{extra[ip]} User:{extra[user]} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'security',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notificaciones',
            ],
        },
    },
]

WSGI_APPLICATION = 'ZenMindConnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Database configuration
# Para desarrollo rápido, usa SQLite. Para producción, cambia a Oracle en .env
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='127.0.0.1:1521/xe'),
            'USER': config('DB_USER', default='ZenMindConnect_mente'),
            'PASSWORD': config('DB_PASSWORD', default='db_mente'),
            'TEST': {
                'USER': 'default_test',
                'TBLSPACE': 'default_test_tbls',
                'TBLSPACE_TMP': 'default_test_tbls_tmp',
            },
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'  # Cambiado a español para la aplicación

TIME_ZONE = 'America/Santiago'

USE_L10N = True

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# Todas las credenciales DEBEN estar en .env. Sin defaults por seguridad.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp-mail.outlook.com')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Sin default - debe estar en .env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Sin default - debe estar en .env

# Security Settings
# Aplicar siempre, incluso en desarrollo (mejor seguridad)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookies seguras (solo en producción con HTTPS)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Headers de seguridad adicionales
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
# COEP puede bloquear iframes de YouTube/Vimeo, lo desactivamos para permitir embeds
# SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'  # Comentado para permitir videos embebidos

# Content Security Policy (CSP) - Protección avanzada contra XSS
CSP_DEFAULT_SRC = "'self'"
CSP_SCRIPT_SRC = "'self' 'unsafe-inline' https://code.jquery.com https://cdn.jsdelivr.net https://cdn.ckeditor.com"
CSP_STYLE_SRC = "'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://cdn.ckeditor.com"
CSP_FONT_SRC = "'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com"
CSP_IMG_SRC = "'self' data: https:"
CSP_CONNECT_SRC = "'self' https://cdn.ckeditor.com https://webrtc2-ap-web-1.agora.io https://webrtc2-ap-web-3.agora.io https://webrtc2-2.ap.sd-rtn.com https://webrtc2-4.ap.sd-rtn.com wss://webrtc2-ap-web-1.agora.io wss://webrtc2-ap-web-3.agora.io wss://webrtc2-2.ap.sd-rtn.com wss://webrtc2-4.ap.sd-rtn.com https://api.agora.io"
CSP_FRAME_SRC = "'self' https://www.youtube.com https://youtube.com https://youtu.be https://player.vimeo.com https://vimeo.com"
CSP_FRAME_ANCESTORS = "'none'"

# Protección CSRF mejorada
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'
# Permitir ngrok en desarrollo
# Agregar dominios de ngrok a CSRF_TRUSTED_ORIGINS en .env si es necesario
# Formato: CSRF_TRUSTED_ORIGINS=https://dominio1.ngrok-free.app,https://dominio2.ngrok-free.app
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
# En desarrollo, si no hay dominios configurados, agregar el dominio actual de ngrok
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    # Agregar dominio común de ngrok (se puede actualizar en .env)
    CSRF_TRUSTED_ORIGINS = ['https://miss-proadmission-overpresumptuously.ngrok-free.dev']

# Protección adicional de datos
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB máximo
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB máximo
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Límite de campos en formularios

# Protección de sesión
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_SAVE_EVERY_REQUEST = True  # Renovar sesión en cada request

# Protección contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protección XSS
SECURE_BROWSER_XSS_FILTER = True

# Static files configuration
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Cache Configuration
# Usado para rate limiting y otras funcionalidades
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'zenmind-connect-cache',
        'TIMEOUT': 300,  # 5 minutos por defecto
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Django Channels Configuration para WebSockets
ASGI_APPLICATION = 'ZenMindConnect.asgi.application'

# Channel Layers - Para desarrollo usamos in-memory, para producción usar Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Para desarrollo
        # Para producción, usar Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}
